name: Promote to production

on:
  workflow_dispatch:

jobs:
  run-script-and-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: main
          lfs: true
      - name: Promote main to production
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git push origin main:production -f
